sudo: required

language: python

services:
  - docker-compose

before_script:
  - docker-compose build galactic-cms
  - docker-compose up -d galactic-cms

script:
- docker-exec -it galactic-cms bash -c "pytest --cov-report term --cov"

after_script:
- docker-compose stop galactic-cms