sudo: required

language: python

services:
  - docker-compose

before_script:
  - docker-compose build galactic-cms
  - docker-compose up -d galactic-cms

script:
- pytest --cove-report term --cov

after_script:
- docker-compose stop galactic-cms