version: '2'
services:
  galactic-cms:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - ./:/app
    depends_on:
    - database
  database:
    image: postgres:9
    env_file: .env
    expose:
      - 5432