version: '2'
services:
  galactic-cms:
    container_name: "galactic-cms"
    build: .
    working_dir: "/app"
    ports:
     - "5000:5000"
    volumes:
     - ./:/app
    depends_on:
    - database
    privileged: true
    # entrypoint: bash -c "chmod 777 wait-for-postgres.sh && ./wait-for-postgres.sh db-galactic-cms 5432"
  database:
    command: ["chmod 777 wait-for-postgres.sh", "./wait-for-postgres.sh db-galactic-cms 5432"]
    container_name: "db-galactic-cms"
    image: postgres:9
    env_file: .env
    expose:
      - 5432