"""empty message

Revision ID: 778bdf2b3601
Revises: 66a860d33a3a
Create Date: 2017-08-13 17:19:05.457244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778bdf2b3601'
down_revision = '66a860d33a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('featured_image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'featured_image')
    # ### end Alembic commands ###
